name: Release
on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'
      - name: Validate version
        run: |
          TAG=${GITHUB_REF##*/}
          echo "Tag is $TAG"
          V=`grep -oP '"version": "\K[^"]+' SDK/package.json`
          if [ "$TAG" != "v$V" ]; then
            echo "Tag and package.json version mismatch ($TAG vs v$V)";
            exit 1;
          fi

